import "server-only";

import type { LaborMarketSignals } from "./schemas";

/** Sample POC data. Replace this module with a trusted market-data source later. */
export const CAREERLENS_MARKET_SEED = {
  source_timestamp: "2026-07-18T00:00:00Z",
  postings: [
    {
      job_id: "seed-data-analyst-hcm",
      job_title: "Data Analyst",
      industry: "Công nghệ và dịch vụ số",
      region: "TP. Hồ Chí Minh",
      avg_salary: { min: 12_000_000, max: 22_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "SQL", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Data visualization", importance: 4, is_short_supply: true, is_proprietary: false },
        { skill_name: "Business communication", importance: 4, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "fresher",
      education_requirement: "flexible",
      culture_fit_indicators: ["team_based", "independent"],
      posted_at: "2026-07-10T00:00:00Z",
    },
    {
      job_id: "seed-product-designer-hcm",
      job_title: "Product Designer",
      industry: "Sản phẩm số",
      region: "TP. Hồ Chí Minh",
      avg_salary: { min: 13_000_000, max: 24_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "User research", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Prototyping", importance: 5, is_short_supply: false, is_proprietary: false },
        { skill_name: "Visual communication", importance: 4, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "junior",
      education_requirement: "flexible",
      culture_fit_indicators: ["team_based", "project_based"],
      posted_at: "2026-07-09T00:00:00Z",
    },
    {
      job_id: "seed-automation-technician-danang",
      job_title: "Kỹ thuật viên tự động hóa",
      industry: "Sản xuất công nghiệp",
      region: "Đà Nẵng",
      avg_salary: { min: 10_000_000, max: 18_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "PLC", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Đọc bản vẽ điện", importance: 4, is_short_supply: true, is_proprietary: false },
        { skill_name: "An toàn công nghiệp", importance: 5, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "fresher",
      education_requirement: "vocational",
      culture_fit_indicators: ["hands_on", "fieldwork"],
      posted_at: "2026-07-12T00:00:00Z",
    },
    {
      job_id: "seed-cybersecurity-hcm",
      job_title: "Cybersecurity Analyst",
      industry: "An toàn thông tin",
      region: "TP. Hồ Chí Minh",
      avg_salary: { min: 15_000_000, max: 28_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "Network fundamentals", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Security monitoring", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Incident documentation", importance: 4, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "junior",
      education_requirement: "certificate",
      culture_fit_indicators: ["independent", "team_based"],
      posted_at: "2026-07-14T00:00:00Z",
    },
    {
      job_id: "seed-digital-marketing-hanoi",
      job_title: "Digital Marketing Specialist",
      industry: "Thương mại và truyền thông",
      region: "Hà Nội",
      avg_salary: { min: 11_000_000, max: 20_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "Content strategy", importance: 4, is_short_supply: false, is_proprietary: false },
        { skill_name: "Marketing analytics", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Campaign operations", importance: 4, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "fresher",
      education_requirement: "college",
      culture_fit_indicators: ["team_based", "creativity"],
      posted_at: "2026-07-08T00:00:00Z",
    },
    {
      job_id: "seed-logistics-hanoi",
      job_title: "Điều phối logistics",
      industry: "Logistics và chuỗi cung ứng",
      region: "Hà Nội",
      avg_salary: { min: 10_000_000, max: 17_000_000, currency: "VND", period: "month" },
      required_skills: [
        { skill_name: "Operations planning", importance: 5, is_short_supply: true, is_proprietary: false },
        { skill_name: "Spreadsheet analysis", importance: 4, is_short_supply: false, is_proprietary: false },
        { skill_name: "Vendor communication", importance: 4, is_short_supply: false, is_proprietary: false },
      ],
      experience_level: "fresher",
      education_requirement: "college",
      culture_fit_indicators: ["team_based", "office"],
      posted_at: "2026-07-11T00:00:00Z",
    },
  ],
  trend_summary: [
    {
      career_family: "Dữ liệu và phân tích",
      region: "TP. Hồ Chí Minh",
      posting_growth_rate: 12.4,
      salary_growth_rate: 6.2,
      short_supply_skills: ["SQL", "Data visualization"],
      confidence: 0.82,
    },
    {
      career_family: "An toàn thông tin",
      region: "TP. Hồ Chí Minh",
      posting_growth_rate: 15.1,
      salary_growth_rate: 7.3,
      short_supply_skills: ["Security monitoring", "Network fundamentals"],
      confidence: 0.78,
    },
    {
      career_family: "Tự động hóa công nghiệp",
      region: "Đà Nẵng",
      posting_growth_rate: 9.6,
      salary_growth_rate: 5.1,
      short_supply_skills: ["PLC", "Đọc bản vẽ điện"],
      confidence: 0.68,
    },
  ],
} satisfies LaborMarketSignals;
